### ISSUE TITLE
Failing Tests on Windows 10 + MATLAB R2020a

### ISSUE THREAD

**Issue by RoyiAvital** [oxfordcontrol/osqp-matlab#23] opened 2020-04-25 08:39 UTC
I installed `OSQP` using the official binaries in bintray and the provided script [as instructed in the guide](https://osqp.org/docs/get_started/matlab.html).

I saw the `run_osqp_tests.m` file and ran it.
The result I got is:

```
Failure Summary:

     Name                                             Failed  Incomplete  Reason(s)
    ==============================================================================================
     codegen_mat_tests/test_solve                       X         X       Errored.
    ----------------------------------------------------------------------------------------------
     codegen_mat_tests/test_update_P                    X         X       Errored.
    ----------------------------------------------------------------------------------------------
     codegen_mat_tests/test_update_P_allind             X         X       Errored.
    ----------------------------------------------------------------------------------------------
     codegen_mat_tests/test_update_A                    X         X       Errored.
    ----------------------------------------------------------------------------------------------
     codegen_mat_tests/test_update_A_allind             X         X       Errored.
    ----------------------------------------------------------------------------------------------
     codegen_mat_tests/test_update_P_A_indP_indA        X         X       Errored.
    ----------------------------------------------------------------------------------------------
     codegen_mat_tests/test_update_P_A_indP             X         X       Errored.
    ----------------------------------------------------------------------------------------------
     codegen_mat_tests/test_update_P_A_indA             X         X       Errored.
    ----------------------------------------------------------------------------------------------
     codegen_mat_tests/test_update_P_A_allind           X         X       Errored.
    ----------------------------------------------------------------------------------------------
     codegen_vec_tests/test_solve                       X         X       Errored.
    ----------------------------------------------------------------------------------------------
     codegen_vec_tests/test_update_q                    X         X       Errored.
    ----------------------------------------------------------------------------------------------
     codegen_vec_tests/test_update_l                    X         X       Errored.
    ----------------------------------------------------------------------------------------------
     codegen_vec_tests/test_update_u                    X         X       Errored.
    ----------------------------------------------------------------------------------------------
     codegen_vec_tests/test_update_bounds               X         X       Errored.
    ----------------------------------------------------------------------------------------------
     feasibility_tests/test_feasibility_problem         X                 Failed by verification.
    ----------------------------------------------------------------------------------------------
     unconstrained_tests/test_unconstrained_problem     X                 Failed by verification.
    ----------------------------------------------------------------------------------------------
     update_matrices_tests/test_solve                   X                 Failed by verification.
    ----------------------------------------------------------------------------------------------
     update_matrices_tests/test_update_P                X                 Failed by verification.
    ----------------------------------------------------------------------------------------------
     update_matrices_tests/test_update_P_allind         X                 Failed by verification.
    ----------------------------------------------------------------------------------------------
     update_matrices_tests/test_update_A                X                 Failed by verification.
    ----------------------------------------------------------------------------------------------
     update_matrices_tests/test_update_A_allind         X                 Failed by verification.
    ----------------------------------------------------------------------------------------------
     update_matrices_tests/test_update_P_A_indP_indA    X                 Failed by verification.
    ----------------------------------------------------------------------------------------------
     update_matrices_tests/test_update_P_A_indP         X                 Failed by verification.
    ----------------------------------------------------------------------------------------------
     update_matrices_tests/test_update_P_A_indA         X                 Failed by verification.
    ----------------------------------------------------------------------------------------------
     update_matrices_tests/test_update_P_A_allind       X                 Failed by verification.
```

Looking at the folder tree:

![image](https://user-images.githubusercontent.com/7347975/80275481-20dc5000-86ea-11ea-91dc-d6d4fbfd8d81.png)

It seems something is creating the folders one inside the other.

It seems the code generation procedure is failing.
Any idea?

Any information I can farther provide to assist fixing it?

Thank You.

**Comment by dawnlh** [comment] 2021-03-31 09:56
The same issue on Win10 MATLAB R2018b, looking forward to the solution

**Comment by goulart-paul** [comment] 2021-03-31 11:19
I can't reproduce the error.    Two questions:

1) Does OSQP itself work for you after you install it, i.e. do examples in the documentation like [this one](https://osqp.org/docs/examples/huber.html) work?

2) It seems that the failure is coming from the codegen tests.   Do you have an appropriate compiler and cmake installed on your system?   If you do, what happens if you run the example at the link above, and then run something like `prob.codegen('.')`?

**Comment by gbanjac** [comment] 2021-03-31 11:21
I cannot reproduce the error either. I am using MATLAB R2020b on Windows 10.

**Comment by dawnlh** [comment] 2021-03-31 13:19
> I can't reproduce the error. Two questions:
> 
> 1. Does OSQP itself work for you after you install it, i.e. do examples in the documentation like [this one](https://osqp.org/docs/examples/huber.html) work?
> 2. It seems that the failure is coming from the codegen tests.   Do you have an appropriate compiler and cmake installed on your system?   If you do, what happens if you run the example at the link above, and then run something like `prob.codegen('.')`?

You are right! I forget to configure the cmake, cause this is not needed for osqp's installation but it's necessary for the `codegen` operation. I solved this problem by configuring the CMake and the compiler properly @RoyiAvital .

**Comment by goulart-paul** [comment] 2021-03-31 14:27
In that case I will close the issue, and I will open a new one with a feature request for the Matlab codegen to fail more gracefully if cmake is not found.

**Closed by goulart-paul** 2021-03-31 14:27 UTC
